# Generated by Django 3.0.3 on 2020-02-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': 'fastcampus_user', 'verbose_name_plural': 'fastcampus_user'},
        ),
        migrations.AddField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(default='test@gmai.com', max_length=128, verbose_name='user_email'),
            preserve_default=False,
        ),
    ]
